# Overrides/augments the dynamics properties specified in the URDF.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# No min/max_position override — planning uses arm_macro.xacro's URDF
# <limit> directly.
joint_limits:
  arm_base_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 5.0
  arm_forearm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 12.5
  arm_mount_base_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.5
    has_jerk_limits: true
    max_jerk: 7.5
  arm_shoulder_forearm_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 5.0
  arm_wrist_1_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 12.5
  arm_wrist_2_end_effector_joint:
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 12.5
